### PR TITLE
jest

### PR DESCRIPTION
**Pull request by IbrahimPala1**

### CODE REVIEW

**Review by codermacleod — APPROVED** [review]
Changes reviewed with QE team, Dan, Sanam, and Ibrahim.

**Review by codermacleod — APPROVED** [review]
Reviewed with QE team, Dan, Sanam and Ibrahim for merging.

**Review by sanam-git — APPROVED** [review]
Reviewed and approved changes

**Comment by codermacleod** [comment]
Integrated Jest and Cypress tests with Github actions. This enables testing upon pushing changes to the repository. YML and config file added alongside.

**Pull request merged**
